/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewGame.java
 *
 * Created on Jan 26, 2011, 3:27:02 PM
 */
package bloodbowl.gui.dialog;

/**
 * Class for the New Game Dialog
 * @author Rishinder
 */
import bloodbowl.gui.map.BloodBowl;
import bloodbowl.engine.Game;
import bloodbowl.model.managers.TeamManager;
import bloodbowl.model.teams.TeamType;
import java.awt.FontFormatException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

public class NewGame extends javax.swing.JDialog {

    Game newGameEngine;
    TeamEditor teamEditor;
    TeamManager teamManager;
    BloodBowl gameMap;
    boolean selectTeamA, selectTeamB;
    private boolean startNewGame;
    /************************Constants***********************/
    int TEAM_A = 1, TEAM_B = 2;

    /********************************************************/
    public NewGame() {

        teamManager = new TeamManager();
        newGameEngine = Game.getInstance();
        selectTeamA = false;
        selectTeamB = false;
        initComponents();

        this.setLocationRelativeTo(getRootPane());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        createTeamAButton = new javax.swing.JButton();
        loadTeamARadio = new javax.swing.JRadioButton();
        createTeamARadio = new javax.swing.JRadioButton();
        teamATypeCombo = new javax.swing.JComboBox();
        loadTeamACombo = new javax.swing.JComboBox();
        loadTeamAButton = new javax.swing.JButton();
        teamANameField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        createTeamBButton = new javax.swing.JButton();
        loadTeamBRadio = new javax.swing.JRadioButton();
        createTeamBRadio = new javax.swing.JRadioButton();
        teamBTypeCombo = new javax.swing.JComboBox();
        loadTeamBCombo = new javax.swing.JComboBox();
        loadTeamBButton = new javax.swing.JButton();
        teamBNameField = new javax.swing.JTextField();
        doneButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        errorMsgLabel = new javax.swing.JLabel();

        setTitle("Team Setup");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Team A"));
        jPanel1.setName("jPanel1"); // NOI18N

        createTeamAButton.setText("Create");
        createTeamAButton.setName("CreateButton1"); // NOI18N
        createTeamAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTeamAButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(loadTeamARadio);
        loadTeamARadio.setText("Load Saved Team");
        loadTeamARadio.setName("loadTeamARadio"); // NOI18N
        loadTeamARadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadTeamARadioMouseClicked(evt);
            }
        });
        loadTeamARadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadTeamARadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(createTeamARadio);
        createTeamARadio.setSelected(true);
        createTeamARadio.setText("Create New Team");
        createTeamARadio.setName("createTeamARadio"); // NOI18N
        createTeamARadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createTeamARadioMouseClicked(evt);
            }
        });
        createTeamARadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTeamARadioActionPerformed(evt);
            }
        });

        teamATypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "Elve", "Orc" }));
        teamATypeCombo.setName("CreateTeamCombo1"); // NOI18N

        loadTeamACombo.setEnabled(false);
        loadTeamACombo.setName("LoadTeamCombo1"); // NOI18N

        loadTeamAButton.setText("Load");
        loadTeamAButton.setName("LoadButton1"); // NOI18N
        loadTeamAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadTeamAButtonActionPerformed(evt);
            }
        });

        teamANameField.setText("Team Name");
        teamANameField.setName("teamANameField"); // NOI18N
        teamANameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamANameFieldActionPerformed(evt);
            }
        });
        teamANameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teamANameFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teamANameField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(teamATypeCombo, 0, 153, Short.MAX_VALUE))
                            .addComponent(loadTeamARadio)
                            .addComponent(loadTeamACombo, 0, 154, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loadTeamAButton, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(createTeamAButton, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(createTeamARadio)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(createTeamARadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamATypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamANameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTeamAButton))
                .addGap(18, 18, 18)
                .addComponent(loadTeamARadio)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadTeamACombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadTeamAButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        teamANameField.getAccessibleContext().setAccessibleName("TeamAName");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Team B"));
        jPanel2.setName("jPanel2"); // NOI18N

        createTeamBButton.setText("Create");
        createTeamBButton.setName("CreateButton2"); // NOI18N
        createTeamBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTeamBButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(loadTeamBRadio);
        loadTeamBRadio.setText("Load Saved Team");
        loadTeamBRadio.setName("loadTeamBRadio"); // NOI18N
        loadTeamBRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadTeamBRadioMouseClicked(evt);
            }
        });

        buttonGroup2.add(createTeamBRadio);
        createTeamBRadio.setSelected(true);
        createTeamBRadio.setText("Create New Team");
        createTeamBRadio.setName("createTeamBRadio"); // NOI18N
        createTeamBRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createTeamBRadioMouseClicked(evt);
            }
        });

        teamBTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "Elve", "Orc" }));
        teamBTypeCombo.setName("CreateTeamCombo2"); // NOI18N

        loadTeamBCombo.setEnabled(false);
        loadTeamBCombo.setName("LoadTeamCombo2"); // NOI18N

        loadTeamBButton.setText("Load");
        loadTeamBButton.setName("Loadbutton2"); // NOI18N
        loadTeamBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadTeamBButtonActionPerformed(evt);
            }
        });

        teamBNameField.setText("Team Name");
        teamBNameField.setName("teamBNameField"); // NOI18N
        teamBNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamBNameFieldActionPerformed(evt);
            }
        });
        teamBNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teamBNameFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teamBNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(teamBTypeCombo, 0, 148, Short.MAX_VALUE)
                            .addComponent(loadTeamBRadio)
                            .addComponent(loadTeamBCombo, 0, 148, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loadTeamBButton, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(createTeamBButton, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(createTeamBRadio)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(createTeamBRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamBTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamBNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTeamBButton))
                .addGap(18, 18, 18)
                .addComponent(loadTeamBRadio)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadTeamBCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadTeamBButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        createTeamBButton.getAccessibleContext().setAccessibleName("CreateButton2");

        doneButton.setText("Done");
        doneButton.setName("doneButton"); // NOI18N
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        errorMsgLabel.setName("errorMsgLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(errorMsgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(doneButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doneButton)
                        .addComponent(cancelButton))
                    .addComponent(errorMsgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * handler for Loading Team A radio button
     */
    private void loadTeamARadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadTeamARadioMouseClicked

        if (teamManager.getSavedTeams() != null) {
            DefaultComboBoxModel newCBModel = new DefaultComboBoxModel(teamManager.getSavedTeams().toArray());
            loadTeamACombo.setModel(newCBModel);
            loadTeamACombo.setEnabled(true);
            loadTeamAButton.setEnabled(true);
            teamANameField.setEnabled(false);
            teamATypeCombo.setEnabled(false);
            createTeamAButton.setEnabled(false);
        }
    }//GEN-LAST:event_loadTeamARadioMouseClicked

    /**
     * Handler for Creating Team A radio button
     */
    private void createTeamARadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createTeamARadioMouseClicked

        loadTeamACombo.setEnabled(false);
        loadTeamAButton.setEnabled(false);
        teamANameField.setEnabled(true);
        teamATypeCombo.setEnabled(true);
        createTeamAButton.setEnabled(true);
    }//GEN-LAST:event_createTeamARadioMouseClicked

    /**
     * Handler for Creating Team B radio button
     */
    private void createTeamBRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createTeamBRadioMouseClicked
        teamBTypeCombo.setEnabled(true);
        createTeamBButton.setEnabled(true);
        teamBNameField.setEnabled(true);
        loadTeamBCombo.setEnabled(false);
        loadTeamBButton.setEnabled(false);
    }//GEN-LAST:event_createTeamBRadioMouseClicked

    /**
     * Handler for Loading Team B radio button
     */
    private void loadTeamBRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadTeamBRadioMouseClicked

        DefaultComboBoxModel newCBModel = new DefaultComboBoxModel((teamManager.getSavedTeams()).toArray());
        loadTeamBCombo.setModel(newCBModel);
        teamBTypeCombo.setEnabled(false);
        createTeamBButton.setEnabled(false);
        teamBNameField.setEnabled(false);
        loadTeamBCombo.setEnabled(true);
        loadTeamBButton.setEnabled(true);
    }//GEN-LAST:event_loadTeamBRadioMouseClicked

    /**
     * Method for Creating Team A on button press
     */
    private void createTeamAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTeamAButtonActionPerformed

        //Create team if name does not conflicts with another team's name
        if (!(teamManager.getSavedTeams()).contains(teamANameField.getText().toLowerCase()))
        {
            if (teamATypeCombo.getSelectedIndex() == 0)
            {
                teamManager.createTeam(TEAM_A, TeamType.HUMAN_TYPE, teamANameField.getText());
            }
            else if (teamATypeCombo.getSelectedIndex() == 1)
            {
                teamManager.createTeam(TEAM_A, TeamType.ELF_TYPE, teamANameField.getText());
            }
            else if (teamATypeCombo.getSelectedIndex() == 2)
            {
                teamManager.createTeam(TEAM_A, TeamType.ORC_TYPE, teamANameField.getText());
            }
            teamEditor = new TeamEditor(teamManager.getTeam(), this);

            teamEditor.setModal(true);
            teamEditor.refreshEditor();
            teamEditor.setVisible(true);

            newGameEngine.setTeamA(teamManager.getTeam());
            errorMsgLabel.setText("");
        }
        else
        {
            errorMsgLabel.setText("*The team with the same name exists. See saved teams list.");
        }
    }//GEN-LAST:event_createTeamAButtonActionPerformed

    /**
     * Method for Creating Team B on button press
     */
    private void createTeamBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTeamBButtonActionPerformed
        //Create team if name does not conflicts with another team's name
        if (!(teamManager.getSavedTeams()).contains(teamBNameField.getText().toLowerCase()))
        {
            if (teamBTypeCombo.getSelectedIndex() == 0)
            {
                teamManager.createTeam(TEAM_B, TeamType.HUMAN_TYPE, teamBNameField.getText());
            }
            else if (teamBTypeCombo.getSelectedIndex() == 1)
            {
                teamManager.createTeam(TEAM_B, TeamType.ELF_TYPE, teamBNameField.getText());
            }
            else if (teamBTypeCombo.getSelectedIndex() == 2)
            {
                teamManager.createTeam(TEAM_B, TeamType.ORC_TYPE, teamBNameField.getText());
            }
            teamEditor = new TeamEditor(teamManager.getTeam(), this);

            teamEditor.setModal(true);
            teamEditor.refreshEditor();
            teamEditor.setVisible(true);

            newGameEngine.setTeamB(teamManager.getTeam());
            errorMsgLabel.setText("");
        }
        else
        {
            errorMsgLabel.setText("*The team with the same name exists. See saved teams list.");
        }
    }//GEN-LAST:event_createTeamBButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        if (selectTeamA && selectTeamB) {
            try {
                this.setVisible(false);
                gameMap = new BloodBowl();
                gameMap.setVisible(true);
                startNewGame = true;
            } catch (FontFormatException ex) {
                Logger.getLogger(NewGame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(NewGame.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            errorMsgLabel.setText("Select both the teams and then hit create");
        }
    }//GEN-LAST:event_doneButtonActionPerformed

    /**
     * Method to inform the dialog that create team A options should be disabled
     */
    public void commitTeamA() {
        selectTeamA = true;
        loadTeamARadio.setEnabled(false);
        createTeamARadio.setEnabled(false);
        loadTeamACombo.setEnabled(false);
        loadTeamAButton.setEnabled(false);
        teamATypeCombo.setEnabled(false);
        createTeamAButton.setEnabled(false);
        teamANameField.setEnabled(false);
    }

    /**
     * Method to inform the dialog that create team B options should be disabled
     */
    public void commitTeamB() {
        selectTeamB = true;
        loadTeamBRadio.setEnabled(false);
        createTeamBRadio.setEnabled(false);
        teamBTypeCombo.setEnabled(false);
        createTeamBButton.setEnabled(false);
        loadTeamBCombo.setEnabled(false);
        loadTeamBButton.setEnabled(false);
        teamBNameField.setEnabled(false);
    }

    public boolean isStartNewGame() {
        return startNewGame;
    }

    public void setStartNewGame(boolean startNewGame) {
        this.startNewGame = startNewGame;
    }

    private void teamANameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamANameFieldActionPerformed
        teamANameField.setText("");
    }//GEN-LAST:event_teamANameFieldActionPerformed

    private void teamBNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamBNameFieldActionPerformed
        teamBNameField.setText("");
    }//GEN-LAST:event_teamBNameFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        startNewGame = false;
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    //Mouse Clicking should clear the text field.
    //Mouse Clicking should clear the text field.
    private void teamANameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teamANameFieldFocusGained
        teamANameField.setText(null);
    }//GEN-LAST:event_teamANameFieldFocusGained

    private void teamBNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teamBNameFieldFocusGained
        teamBNameField.setText(null);
    }//GEN-LAST:event_teamBNameFieldFocusGained

    private void loadTeamARadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadTeamARadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadTeamARadioActionPerformed

    private void createTeamARadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTeamARadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createTeamARadioActionPerformed

    /**
     * Method to load a team from the list of created teams for team A
     */
    private void loadTeamAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadTeamAButtonActionPerformed
        try {
            if (loadTeamACombo.getSelectedItem() != null) {
                teamManager.restoreTeam(loadTeamACombo.getSelectedItem().toString(), TEAM_A);
                newGameEngine.setTeamA(teamManager.getTeam());
                this.commitTeamA();
            }
        } catch (IOException ex) {
            Logger.getLogger(NewGame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadTeamAButtonActionPerformed

    /**
     * Method to load a team from the list of created teams for team B
     */
    private void loadTeamBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadTeamBButtonActionPerformed
        try {
            if (loadTeamBCombo.getSelectedItem() != null) {
                teamManager.restoreTeam(loadTeamBCombo.getSelectedItem().toString(), TEAM_B);
                newGameEngine.setTeamB(teamManager.getTeam());
                this.commitTeamB();
            }
        } catch (IOException ex) {
            Logger.getLogger(NewGame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadTeamBButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewGame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createTeamAButton;
    private javax.swing.JRadioButton createTeamARadio;
    private javax.swing.JButton createTeamBButton;
    private javax.swing.JRadioButton createTeamBRadio;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel errorMsgLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loadTeamAButton;
    private javax.swing.JComboBox loadTeamACombo;
    private javax.swing.JRadioButton loadTeamARadio;
    private javax.swing.JButton loadTeamBButton;
    private javax.swing.JComboBox loadTeamBCombo;
    private javax.swing.JRadioButton loadTeamBRadio;
    private javax.swing.JTextField teamANameField;
    private javax.swing.JComboBox teamATypeCombo;
    private javax.swing.JTextField teamBNameField;
    private javax.swing.JComboBox teamBTypeCombo;
    // End of variables declaration//GEN-END:variables
}
