/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SaveGame.java
 *
 * Created on Mar 4, 2011, 7:31:42 PM
 */
package bloodbowl.gui.dialog;

import bloodbowl.engine.BloodBowlException;
import bloodbowl.engine.Game;
import bloodbowl.model.managers.GameManager;
import javax.swing.JOptionPane;

/**
 *
 * @author singh
 */
public class SaveGame extends javax.swing.JFrame {

    Game gameEngine;

    /** Creates new form SaveGame */
    public SaveGame() {
        initComponents();

        this.setLocationRelativeTo(getRootPane());
    }

    public SaveGame(Game gameEngine) {
        initComponents();

        this.gameEngine = gameEngine;

        this.setLocationRelativeTo(getRootPane());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameNameText = new javax.swing.JTextField();
        saveGameBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gameNameText.setText("Game Name");
        gameNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameNameTextActionPerformed(evt);
            }
        });

        saveGameBtn.setText("Save Game");
        saveGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGameBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveGameBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(cancelBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveGameBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gameNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameNameTextActionPerformed

    private void saveGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGameBtnActionPerformed
        GameManager gameManager = GameManager.getInstance();
        gameManager.setGameEngine(gameEngine);

        try {
            gameManager.saveGame(gameNameText.getText());

            JOptionPane.showMessageDialog(null, "Game saved successfully!");
        } catch (BloodBowlException ex) {
             JOptionPane.showConfirmDialog(this, ex.getMessage(), "BloodBowl", JOptionPane.OK_OPTION);
        }
        this.setVisible(false);
    }//GEN-LAST:event_saveGameBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SaveGame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField gameNameText;
    private javax.swing.JButton saveGameBtn;
    // End of variables declaration//GEN-END:variables
}
